<?php

use App\Http\Controllers\Admin\AlbumController;
use App\Http\Controllers\Admin\AlbumTrackController;
use App\Http\Controllers\Admin\AnimatedEpisodeController;
use App\Http\Controllers\Admin\AnimatedSeasonController;
use App\Http\Controllers\Admin\AnimatedSeriesController;
use App\Http\Controllers\Admin\AudiobookChapterController;
use App\Http\Controllers\Admin\AudiobookController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\BookFileController;
use App\Http\Controllers\Admin\CartoonController;
use App\Http\Controllers\Admin\CartoonFileController;
use App\Http\Controllers\Admin\CredentialController;
use App\Http\Controllers\Admin\EpisodeController;
use App\Http\Controllers\Admin\FileEntryController;
use App\Http\Controllers\Admin\FileEntryFileController;
use App\Http\Controllers\Admin\GalleryAlbumController;
use App\Http\Controllers\Admin\GalleryItemController;
use App\Http\Controllers\Admin\GameController;
use App\Http\Controllers\Admin\GameFileController;
use App\Http\Controllers\Admin\MovieController;
use App\Http\Controllers\Admin\MovieFileController;
use App\Http\Controllers\Admin\SeasonController;
use App\Http\Controllers\Admin\SeriesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LibraryAnimatedSeriesMediaController;
use App\Http\Controllers\LibraryAudiobookMediaController;
use App\Http\Controllers\LibraryBookMediaController;
use App\Http\Controllers\LibraryCartoonMediaController;
use App\Http\Controllers\LibraryController;
use App\Http\Controllers\LibraryFileMediaController;
use App\Http\Controllers\LibraryGalleryMediaController;
use App\Http\Controllers\LibraryGameMediaController;
use App\Http\Controllers\LibraryMovieMediaController;
use App\Http\Controllers\LibraryMusicMediaController;
use App\Http\Controllers\LibrarySeriesMediaController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/library/movie/{movie}/poster', [LibraryMovieMediaController::class, 'poster'])->name('library.movie.poster');
Route::get('/library/movie/{movie}/files/{file}/stream', [LibraryMovieMediaController::class, 'stream'])->name('library.movie.stream');
Route::get('/library/movie/{movie}', [LibraryController::class, 'movie'])->name('library.movie');
Route::get('/library/series/{series}/poster', [LibrarySeriesMediaController::class, 'poster'])->name('library.series.poster');
Route::get('/library/series/{series}/episodes/{episode}/stream', [LibrarySeriesMediaController::class, 'stream'])->name('library.series.stream');
Route::get('/library/series/{series}', [LibraryController::class, 'series'])->name('library.series');
Route::get('/library/cartoon/{cartoon}/poster', [LibraryCartoonMediaController::class, 'poster'])->name('library.cartoon.poster');
Route::get('/library/cartoon/{cartoon}/files/{file}/stream', [LibraryCartoonMediaController::class, 'stream'])->name('library.cartoon.stream');
Route::get('/library/cartoon/{cartoon}', [LibraryController::class, 'cartoon'])->name('library.cartoon');
Route::get('/library/animated_series/{animatedSeries}/poster', [LibraryAnimatedSeriesMediaController::class, 'poster'])->name('library.animated-series.poster');
Route::get('/library/animated_series/{animatedSeries}/episodes/{animatedEpisode}/stream', [LibraryAnimatedSeriesMediaController::class, 'stream'])->name('library.animated-series.stream');
Route::get('/library/animated_series/{animatedSeries}', [LibraryController::class, 'animatedSeries'])->name('library.animated-series');
Route::get('/library/music/{album}/poster', [LibraryMusicMediaController::class, 'poster'])->name('library.music.poster');
Route::get('/library/music/{album}/tracks/{track}/stream', [LibraryMusicMediaController::class, 'stream'])->name('library.music.stream');
Route::get('/library/music/{album}', [LibraryController::class, 'album'])->name('library.music');
Route::get('/library/book/{book}/poster', [LibraryBookMediaController::class, 'poster'])->name('library.book.poster');
Route::get('/library/book/{book}/files/{file}/stream', [LibraryBookMediaController::class, 'stream'])->name('library.book.stream');
Route::get('/library/book/{book}', [LibraryController::class, 'book'])->name('library.book');
Route::get('/library/audiobook/{audiobook}/poster', [LibraryAudiobookMediaController::class, 'poster'])->name('library.audiobook.poster');
Route::get('/library/audiobook/{audiobook}/chapters/{chapter}/stream', [LibraryAudiobookMediaController::class, 'stream'])->name('library.audiobook.stream');
Route::get('/library/audiobook/{audiobook}', [LibraryController::class, 'audiobook'])->name('library.audiobook');
Route::get('/library/file/{fileEntry}/files/{file}/stream', [LibraryFileMediaController::class, 'stream'])->name('library.file.stream');
Route::get('/library/file/{fileEntry}', [LibraryController::class, 'fileEntry'])->name('library.file');
Route::get('/library/game/{game}/poster', [LibraryGameMediaController::class, 'poster'])->name('library.game.poster');
Route::get('/library/game/{game}/files/{file}/download', [LibraryGameMediaController::class, 'download'])->name('library.game.download');
Route::get('/library/game/{game}', [LibraryController::class, 'game'])->name('library.game');
Route::get('/library/gallery/{galleryAlbum}/poster', [LibraryGalleryMediaController::class, 'poster'])->name('library.gallery.poster');
Route::get('/library/gallery/{galleryAlbum}/items/{item}/stream', [LibraryGalleryMediaController::class, 'stream'])->name('library.gallery.stream');
Route::get('/library/gallery/{galleryAlbum}', [LibraryController::class, 'galleryAlbum'])->name('library.gallery');
Route::get('/library/{type}', [LibraryController::class, 'show'])->name('library.show');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/movies', [MovieController::class, 'index'])->name('movies');
        Route::get('/movies/create', [MovieController::class, 'create'])->name('movies.create');
        Route::post('/movies', [MovieController::class, 'store'])->name('movies.store');
        Route::get('/movies/{movie}/edit', [MovieController::class, 'edit'])->name('movies.edit');
        Route::put('/movies/{movie}', [MovieController::class, 'update'])->name('movies.update');
        Route::delete('/movies/{movie}', [MovieController::class, 'destroy'])->name('movies.destroy');
        Route::get('/movies/files/search', [MovieFileController::class, 'search'])->name('movies.files.search');
        Route::get('/movies/{movie}/files/create', [MovieFileController::class, 'create'])->name('movies.files.create');
        Route::post('/movies/{movie}/files', [MovieFileController::class, 'store'])->name('movies.files.store');
        Route::delete('/movies/{movie}/files/{file}', [MovieFileController::class, 'destroy'])->name('movies.files.destroy');
        Route::get('/series', [SeriesController::class, 'index'])->name('series');
        Route::get('/series/create', [SeriesController::class, 'create'])->name('series.create');
        Route::post('/series', [SeriesController::class, 'store'])->name('series.store');
        Route::get('/series/episodes/search', [EpisodeController::class, 'search'])->name('series.episodes.search');
        Route::get('/series/{series}/edit', [SeriesController::class, 'edit'])->name('series.edit');
        Route::put('/series/{series}', [SeriesController::class, 'update'])->name('series.update');
        Route::delete('/series/{series}', [SeriesController::class, 'destroy'])->name('series.destroy');
        Route::post('/series/{series}/seasons', [SeasonController::class, 'store'])->name('series.seasons.store');
        Route::delete('/series/{series}/seasons/{season}', [SeasonController::class, 'destroy'])->name('series.seasons.destroy');
        Route::get('/series/{series}/seasons/{season}/episodes/create', [EpisodeController::class, 'create'])->name('series.episodes.create');
        Route::post('/series/{series}/seasons/{season}/episodes', [EpisodeController::class, 'store'])->name('series.episodes.store');
        Route::delete('/series/{series}/seasons/{season}/episodes/{episode}', [EpisodeController::class, 'destroy'])->name('series.episodes.destroy');
        Route::get('/cartoons', [CartoonController::class, 'index'])->name('cartoons');
        Route::get('/cartoons/create', [CartoonController::class, 'create'])->name('cartoons.create');
        Route::post('/cartoons', [CartoonController::class, 'store'])->name('cartoons.store');
        Route::get('/cartoons/files/search', [CartoonFileController::class, 'search'])->name('cartoons.files.search');
        Route::get('/cartoons/{cartoon}/edit', [CartoonController::class, 'edit'])->name('cartoons.edit');
        Route::put('/cartoons/{cartoon}', [CartoonController::class, 'update'])->name('cartoons.update');
        Route::delete('/cartoons/{cartoon}', [CartoonController::class, 'destroy'])->name('cartoons.destroy');
        Route::get('/cartoons/{cartoon}/files/create', [CartoonFileController::class, 'create'])->name('cartoons.files.create');
        Route::post('/cartoons/{cartoon}/files', [CartoonFileController::class, 'store'])->name('cartoons.files.store');
        Route::delete('/cartoons/{cartoon}/files/{file}', [CartoonFileController::class, 'destroy'])->name('cartoons.files.destroy');
        Route::get('/animated-series', [AnimatedSeriesController::class, 'index'])->name('animated-series');
        Route::get('/animated-series/create', [AnimatedSeriesController::class, 'create'])->name('animated-series.create');
        Route::post('/animated-series', [AnimatedSeriesController::class, 'store'])->name('animated-series.store');
        Route::get('/animated-series/episodes/search', [AnimatedEpisodeController::class, 'search'])->name('animated-series.episodes.search');
        Route::get('/animated-series/{animatedSeries}/edit', [AnimatedSeriesController::class, 'edit'])->name('animated-series.edit');
        Route::put('/animated-series/{animatedSeries}', [AnimatedSeriesController::class, 'update'])->name('animated-series.update');
        Route::delete('/animated-series/{animatedSeries}', [AnimatedSeriesController::class, 'destroy'])->name('animated-series.destroy');
        Route::post('/animated-series/{animatedSeries}/seasons', [AnimatedSeasonController::class, 'store'])->name('animated-series.seasons.store');
        Route::delete('/animated-series/{animatedSeries}/seasons/{animatedSeason}', [AnimatedSeasonController::class, 'destroy'])->name('animated-series.seasons.destroy');
        Route::get('/animated-series/{animatedSeries}/seasons/{animatedSeason}/episodes/create', [AnimatedEpisodeController::class, 'create'])->name('animated-series.episodes.create');
        Route::post('/animated-series/{animatedSeries}/seasons/{animatedSeason}/episodes', [AnimatedEpisodeController::class, 'store'])->name('animated-series.episodes.store');
        Route::delete('/animated-series/{animatedSeries}/seasons/{animatedSeason}/episodes/{animatedEpisode}', [AnimatedEpisodeController::class, 'destroy'])->name('animated-series.episodes.destroy');
        Route::get('/music', [AlbumController::class, 'index'])->name('music');
        Route::get('/music/create', [AlbumController::class, 'create'])->name('music.create');
        Route::post('/music', [AlbumController::class, 'store'])->name('music.store');
        Route::get('/music/tracks/search', [AlbumTrackController::class, 'search'])->name('music.tracks.search');
        Route::get('/music/{album}/edit', [AlbumController::class, 'edit'])->name('music.edit');
        Route::put('/music/{album}', [AlbumController::class, 'update'])->name('music.update');
        Route::delete('/music/{album}', [AlbumController::class, 'destroy'])->name('music.destroy');
        Route::get('/music/{album}/tracks/create', [AlbumTrackController::class, 'create'])->name('music.tracks.create');
        Route::post('/music/{album}/tracks', [AlbumTrackController::class, 'store'])->name('music.tracks.store');
        Route::delete('/music/{album}/tracks/{track}', [AlbumTrackController::class, 'destroy'])->name('music.tracks.destroy');
        Route::get('/books', [BookController::class, 'index'])->name('books');
        Route::get('/books/create', [BookController::class, 'create'])->name('books.create');
        Route::post('/books', [BookController::class, 'store'])->name('books.store');
        Route::get('/books/files/search', [BookFileController::class, 'search'])->name('books.files.search');
        Route::get('/books/{book}/edit', [BookController::class, 'edit'])->name('books.edit');
        Route::put('/books/{book}', [BookController::class, 'update'])->name('books.update');
        Route::delete('/books/{book}', [BookController::class, 'destroy'])->name('books.destroy');
        Route::get('/books/{book}/files/create', [BookFileController::class, 'create'])->name('books.files.create');
        Route::post('/books/{book}/files', [BookFileController::class, 'store'])->name('books.files.store');
        Route::delete('/books/{book}/files/{file}', [BookFileController::class, 'destroy'])->name('books.files.destroy');
        Route::get('/audiobooks', [AudiobookController::class, 'index'])->name('audiobooks');
        Route::get('/audiobooks/create', [AudiobookController::class, 'create'])->name('audiobooks.create');
        Route::post('/audiobooks', [AudiobookController::class, 'store'])->name('audiobooks.store');
        Route::get('/audiobooks/chapters/search', [AudiobookChapterController::class, 'search'])->name('audiobooks.chapters.search');
        Route::get('/audiobooks/{audiobook}/edit', [AudiobookController::class, 'edit'])->name('audiobooks.edit');
        Route::put('/audiobooks/{audiobook}', [AudiobookController::class, 'update'])->name('audiobooks.update');
        Route::delete('/audiobooks/{audiobook}', [AudiobookController::class, 'destroy'])->name('audiobooks.destroy');
        Route::get('/audiobooks/{audiobook}/chapters/create', [AudiobookChapterController::class, 'create'])->name('audiobooks.chapters.create');
        Route::post('/audiobooks/{audiobook}/chapters', [AudiobookChapterController::class, 'store'])->name('audiobooks.chapters.store');
        Route::delete('/audiobooks/{audiobook}/chapters/{chapter}', [AudiobookChapterController::class, 'destroy'])->name('audiobooks.chapters.destroy');
        Route::get('/files', [FileEntryController::class, 'index'])->name('files');
        Route::get('/files/create', [FileEntryController::class, 'create'])->name('files.create');
        Route::post('/files', [FileEntryController::class, 'store'])->name('files.store');
        Route::get('/files/attachments/search', [FileEntryFileController::class, 'search'])->name('files.attachments.search');
        Route::get('/files/{fileEntry}/edit', [FileEntryController::class, 'edit'])->name('files.edit');
        Route::put('/files/{fileEntry}', [FileEntryController::class, 'update'])->name('files.update');
        Route::delete('/files/{fileEntry}', [FileEntryController::class, 'destroy'])->name('files.destroy');
        Route::get('/files/{fileEntry}/attachments/create', [FileEntryFileController::class, 'create'])->name('files.attachments.create');
        Route::post('/files/{fileEntry}/attachments', [FileEntryFileController::class, 'store'])->name('files.attachments.store');
        Route::delete('/files/{fileEntry}/attachments/{file}', [FileEntryFileController::class, 'destroy'])->name('files.attachments.destroy');
        Route::get('/games', [GameController::class, 'index'])->name('games');
        Route::get('/games/create', [GameController::class, 'create'])->name('games.create');
        Route::post('/games', [GameController::class, 'store'])->name('games.store');
        Route::get('/games/files/search', [GameFileController::class, 'search'])->name('games.files.search');
        Route::get('/games/{game}/edit', [GameController::class, 'edit'])->name('games.edit');
        Route::put('/games/{game}', [GameController::class, 'update'])->name('games.update');
        Route::delete('/games/{game}', [GameController::class, 'destroy'])->name('games.destroy');
        Route::get('/games/{game}/files/create', [GameFileController::class, 'create'])->name('games.files.create');
        Route::post('/games/{game}/files', [GameFileController::class, 'store'])->name('games.files.store');
        Route::delete('/games/{game}/files/{file}', [GameFileController::class, 'destroy'])->name('games.files.destroy');
        Route::get('/gallery', [GalleryAlbumController::class, 'index'])->name('gallery');
        Route::get('/gallery/create', [GalleryAlbumController::class, 'create'])->name('gallery.create');
        Route::post('/gallery', [GalleryAlbumController::class, 'store'])->name('gallery.store');
        Route::get('/gallery/items/search', [GalleryItemController::class, 'search'])->name('gallery.items.search');
        Route::get('/gallery/{galleryAlbum}/edit', [GalleryAlbumController::class, 'edit'])->name('gallery.edit');
        Route::put('/gallery/{galleryAlbum}', [GalleryAlbumController::class, 'update'])->name('gallery.update');
        Route::delete('/gallery/{galleryAlbum}', [GalleryAlbumController::class, 'destroy'])->name('gallery.destroy');
        Route::get('/gallery/{galleryAlbum}/items/create', [GalleryItemController::class, 'create'])->name('gallery.items.create');
        Route::post('/gallery/{galleryAlbum}/items', [GalleryItemController::class, 'store'])->name('gallery.items.store');
        Route::delete('/gallery/{galleryAlbum}/items/{item}', [GalleryItemController::class, 'destroy'])->name('gallery.items.destroy');
        Route::get('/credentials', [CredentialController::class, 'index'])->name('credentials');
        Route::get('/credentials/create', [CredentialController::class, 'create'])->name('credentials.create');
        Route::post('/credentials', [CredentialController::class, 'store'])->name('credentials.store');
        Route::get('/credentials/{credential}/edit', [CredentialController::class, 'edit'])->name('credentials.edit');
        Route::put('/credentials/{credential}', [CredentialController::class, 'update'])->name('credentials.update');
        Route::delete('/credentials/{credential}', [CredentialController::class, 'destroy'])->name('credentials.destroy');
        Route::view('/other', 'admin.category', ['title' => 'Остальное'])->name('other');
        Route::view('/documents', 'admin.category', ['title' => 'Документы'])->name('documents');
    });
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
